import type {
  AnalysisReport,
  EvidencePair,
  RemediationRecord,
  Verification,
  VerificationCertificate,
} from '@/types/analysis';

/**
 * The engine, over HTTP.
 *
 * Three sources feed the deck, in this order of trust:
 *
 *   1. `window.__PREFLIGHT_REPORT__` — the CLI injected a real run into
 *      report.html. Already on the page, needs no network.
 *   2. This API — `preflight serve` is running and has real runs on disk.
 *   3. The demo fixture — itself generated by a real run, not authored.
 *
 * Every call fails soft. A deck that renders the fixture is useful; a deck
 * that renders a stack trace because the API is not running is not, and the
 * API being absent is the normal state when someone opens a report.html
 * someone else emailed them.
 */

const BASE = (import.meta.env.VITE_PREFLIGHT_API as string | undefined) ?? 'http://127.0.0.1:8000';

/** The byte-range media route for a run recorded in lineage. Every report
 * carries a portable relative `video.srcUrl` (correct beside a standalone
 * report.html); inside the dashboard's origin that path resolves to nothing,
 * so any report served through this API must have its video URL rewritten
 * through here instead. */
export function runMediaUrl(runId: string): string {
  return `${BASE}/api/runs/${encodeURIComponent(runId)}/media`;
}

/** Long enough for a real analysis, short enough that a dead port is obvious. */
const ANALYZE_TIMEOUT_MS = 15 * 60 * 1000;
const READ_TIMEOUT_MS = 4000;

export interface RunSummary {
  id: string;
  filename: string;
  durationMs: number;
  overall: number | null;
  verdict: string | null;
  weakest: string | null;
  findingCount: number;
  coverage: number | null;
  analyzedAt: string | null;
}

export interface Health {
  status: string;
  engineVersion: string;
  ffmpeg: string | null;
  ffmpegAvailable: boolean;
  online: boolean;
  capabilities: Record<string, { tier: string; degraded: boolean }>;
  capabilitySummary: { preferred: number; fallback: number; unavailable: number };
}

async function call<T>(path: string, init?: RequestInit, timeoutMs = READ_TIMEOUT_MS): Promise<T> {
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), timeoutMs);
  try {
    const response = await fetch(`${BASE}${path}`, { ...init, signal: controller.signal });
    if (!response.ok) {
      // The API answers errors as JSON; fall back to the status line when it
      // is something else entirely (a proxy, a wrong port).
      const detail = await response.json().catch(() => ({ error: response.statusText }));
      throw new Error(detail.error ?? `HTTP ${response.status}`);
    }
    return (await response.json()) as T;
  } finally {
    clearTimeout(timer);
  }
}

/** Null when the API is not reachable — never throws. */
export async function fetchHealth(): Promise<Health | null> {
  try {
    return await call<Health>('/api/health');
  } catch {
    return null;
  }
}

export async function fetchRuns(): Promise<RunSummary[]> {
  try {
    const data = await call<{ runs: RunSummary[] }>('/api/runs');
    return data.runs;
  } catch {
    return [];
  }
}

export async function fetchRun(id: string): Promise<AnalysisReport | null> {
  try {
    const report = await call<AnalysisReport>(`/api/runs/${encodeURIComponent(id)}`);
    // API reports are stored as portable standalone artifacts, whose relative
    // video URL is correct beside report.html but not inside the dashboard's
    // origin. The server resolves this id through lineage and supports ranges
    // so the player can seek the exact evidence timestamp.
    return {
      ...report,
      video: {
        ...report.video,
        srcUrl: runMediaUrl(id),
      },
    };
  } catch {
    return null;
  }
}

/** The most recent run on the server, or null when there are none. */
export async function fetchLatestRun(): Promise<AnalysisReport | null> {
  const runs = await fetchRuns();
  return runs.length > 0 ? fetchRun(runs[0].id) : null;
}

/**
 * Send a video to the engine and get back the path it landed on.
 *
 * Uses browser-owned multipart encoding. Unicode filenames are not valid
 * arbitrary HTTP header values, so the name belongs in the form body.
 */
export async function uploadVideo(
  file: File,
  timeoutMs = 30 * 60 * 1000,
): Promise<{ path: string; name: string; bytes: number }> {
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), timeoutMs);
  try {
    const body = new FormData();
    body.append('file', file, file.name);
    const response = await fetch(`${BASE}/api/upload`, {
      method: 'POST',
      // The browser provides the multipart boundary; never put file.name in a header.
      body,
      signal: controller.signal,
    });
    if (!response.ok) {
      const detail = await response.json().catch(() => ({ error: response.statusText }));
      throw new Error(detail.error ?? `upload failed (${response.status})`);
    }
    return await response.json();
  } finally {
    clearTimeout(timer);
  }
}

export interface StageEvent {
  seq: number;
  type:
    | 'run.start'
    | 'stage.start'
    | 'stage.end'
    | 'run.complete'
    | 'run.error'
    | 'fix.progress';
  stage?: string;
  agentId?: string;
  name?: string;
  status?: string;
  coverage?: number;
  elapsedMs?: number;
  findings?: number;
  calls?: number;
  detail?: string;
  error?: string;
  id?: string;
  topology?: { id: string; tier: number; parents: string[] }[];
  /** fix.progress only — which phase of the render is running. */
  stage_label?: string;
  /** fix.progress only — the persisted lifecycle state the engine just
   * entered. Sent by the backend rather than inferred here, so the strip on
   * screen and the stored transition history cannot disagree. */
  state?: string;
  reused?: boolean;
  ops?: number;
  output?: string;
  rendered?: boolean;
  /** A measurement of the rendered artifact, supplied only after the
   * verification pass has completed successfully. */
  afterReport?: AnalysisReport;

  /* ---- the closed loop's terminal payload ------------------------- */

  /** The comparison between the two runs. Present on `run.complete` for a
   * remediation that reached a verdict. */
  verification?: Verification;
  certificate?: VerificationCertificate;
  evidence?: EvidencePair[];
  telemetry?: Record<string, unknown>;
  lifecycle?: RemediationRecord;
  verdict?: string;
  remediationId?: string;
  certificateId?: string;
  verificationId?: string;
  /** The runs-table id the rendered artifact's media is recorded under.
   * Distinct from `verificationId` (the VER-#### comparison record) —
   * this is the one `runMediaUrl` needs. */
  verificationRunId?: string;
  sourceRunId?: string;
  /** Set when this run picked up a remediation an earlier process left
   * unfinished — names the state it was interrupted in. */
  resumedFrom?: string;
  interruptedAt?: string;
}

export interface InterruptedRemediation {
  remediationId: string;
  state: string;
  describe: string;
  resumesAt: string | null;
}

/**
 * Remediations the engine has on disk, including ones a crash left open.
 *
 * Asked once at startup. This is what makes a restart informative rather than
 * lossy: the deck can say "REM-0001 was interrupted during REANALYSING"
 * instead of behaving as though the operation never happened.
 */
export async function fetchRemediations(): Promise<{
  remediations: RemediationRecord[];
  interrupted: InterruptedRemediation[];
}> {
  try {
    return await call<{
      remediations: RemediationRecord[];
      interrupted: InterruptedRemediation[];
    }>('/api/remediations');
  } catch {
    return { remediations: [], interrupted: [] };
  }
}

/** One remediation resolved through to its certificate, or null. */
export async function fetchRemediation(id: string): Promise<
  | (RemediationRecord & {
      verification?: Verification;
      certificate?: VerificationCertificate;
      telemetry?: Record<string, unknown>;
      certificateIntegrity?: 'VALID' | 'MISMATCH';
    })
  | null
> {
  try {
    return await call(`/api/remediations/${encodeURIComponent(id)}`);
  } catch {
    return null;
  }
}

interface JobSnapshot {
  id: string;
  done: boolean;
  error: string | null;
  events: StageEvent[];
}

async function fetchJob(id: string): Promise<JobSnapshot | null> {
  try {
    return await call<JobSnapshot>(`/api/jobs/${encodeURIComponent(id)}`);
  } catch {
    return null;
  }
}

/**
 * Start a run and watch it happen.
 *
 * The synchronous route answers only when everything is finished — minutes
 * of silence on a hosted run, which is indistinguishable from a hang. This
 * returns immediately and streams each agent as it starts and settles.
 *
 * Returns a disposer. Call it to stop listening; the analysis continues
 * server-side and its report still lands on disk.
 */
export async function startJob(
  video: string,
  options: { offline?: boolean; budget?: number; strategy?: string },
  onEvent: (event: StageEvent) => void,
): Promise<() => void> {
  const started = await call<{ id: string }>(
    '/api/jobs',
    {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ video, ...options }),
    },
    READ_TIMEOUT_MS,
  );

  const stream = new EventSource(`${BASE}/api/events/${started.id}`);
  let lastSeq = -1;
  let closed = false;
  const deliver = (event: StageEvent) => {
    // SSE is replayable and the reconciliation endpoint returns the same
    // frames. Sequence numbers make delivery idempotent across both paths.
    if (event.seq <= lastSeq) return;
    lastSeq = event.seq;
    onEvent(event);
    if (event.type === 'run.complete' || event.type === 'run.error') close();
  };
  const poll = window.setInterval(() => {
    void (async () => {
      const snapshot = await fetchJob(started.id);
      if (!snapshot || closed) return;
      snapshot.events.forEach(deliver);
      if (snapshot.done && snapshot.error && lastSeq < snapshot.events.length) {
        // A defensive terminal state for an interrupted event write. The
        // backend's stored error is still the source, never a guessed result.
        deliver({ seq: snapshot.events.length, type: 'run.error', error: snapshot.error });
      }
    })();
  }, 1000);
  const close = () => {
    if (closed) return;
    closed = true;
    window.clearInterval(poll);
    stream.close();
  };
  stream.onmessage = (message) => {
    try {
      const event = JSON.parse(message.data) as StageEvent;
      deliver(event);
    } catch {
      /* a malformed frame must not kill the stream */
    }
  };
  // Keep reconciling the authoritative job record if a proxy/browser closes
  // the SSE connection. This is recovery, not a second execution path.
  stream.onerror = () => stream.close();

  return close;
}

/**
 * Compile and render the remediation, streaming progress.
 *
 * The Apply control was a label with no handler — the worst kind of broken,
 * because the plan and the ffmpeg command beside it are both real and only
 * the one button that would act on them did nothing.
 */
export async function applyFix(
  video: string,
  options: { offline?: boolean; strategy?: string },
  onEvent: (event: StageEvent) => void,
): Promise<() => void> {
  const started = await call<{ id: string }>(
    '/api/fix',
    {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ video, ...options }),
    },
    READ_TIMEOUT_MS,
  );

  const stream = new EventSource(`${BASE}/api/events/${started.id}`);
  stream.onmessage = (message) => {
    try {
      const event = JSON.parse(message.data) as StageEvent;
      onEvent(event);
      if (event.type === 'run.complete' || event.type === 'run.error') stream.close();
    } catch {
      /* a malformed frame must not kill the stream */
    }
  };
  stream.onerror = () => stream.close();
  return () => stream.close();
}

export async function analyze(
  video: string,
  options: { offline?: boolean; budget?: number; strategy?: string } = {},
): Promise<{ id: string; report: AnalysisReport }> {
  return call<{ id: string; report: AnalysisReport }>(
    '/api/analyze',
    {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ video, ...options }),
    },
    ANALYZE_TIMEOUT_MS,
  );
}
