import type { AnalysisReport } from '@/types/analysis';

/**
 * The engine, over HTTP.
 *
 * Three sources feed the deck, in this order of trust:
 *
 *   1. `window.__PREFLIGHT_REPORT__` — the CLI injected a real run into
 *      report.html. Already on the page, needs no network.
 *   2. This API — `preflight serve` is running and has real runs on disk.
 *   3. The demo fixture — itself generated by a real run, not authored.
 *
 * Every call fails soft. A deck that renders the fixture is useful; a deck
 * that renders a stack trace because the API is not running is not, and the
 * API being absent is the normal state when someone opens a report.html
 * someone else emailed them.
 */

const BASE = (import.meta.env.VITE_PREFLIGHT_API as string | undefined) ?? 'http://127.0.0.1:8000';

/** Long enough for a real analysis, short enough that a dead port is obvious. */
const ANALYZE_TIMEOUT_MS = 15 * 60 * 1000;
const READ_TIMEOUT_MS = 4000;

export interface RunSummary {
  id: string;
  filename: string;
  durationMs: number;
  overall: number | null;
  verdict: string | null;
  weakest: string | null;
  findingCount: number;
  coverage: number | null;
  analyzedAt: string | null;
}

export interface Health {
  status: string;
  engineVersion: string;
  ffmpeg: string | null;
  ffmpegAvailable: boolean;
  online: boolean;
  capabilities: Record<string, { tier: string; degraded: boolean }>;
  capabilitySummary: { preferred: number; fallback: number; unavailable: number };
}

async function call<T>(path: string, init?: RequestInit, timeoutMs = READ_TIMEOUT_MS): Promise<T> {
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), timeoutMs);
  try {
    const response = await fetch(`${BASE}${path}`, { ...init, signal: controller.signal });
    if (!response.ok) {
      // The API answers errors as JSON; fall back to the status line when it
      // is something else entirely (a proxy, a wrong port).
      const detail = await response.json().catch(() => ({ error: response.statusText }));
      throw new Error(detail.error ?? `HTTP ${response.status}`);
    }
    return (await response.json()) as T;
  } finally {
    clearTimeout(timer);
  }
}

/** Null when the API is not reachable — never throws. */
export async function fetchHealth(): Promise<Health | null> {
  try {
    return await call<Health>('/api/health');
  } catch {
    return null;
  }
}

export async function fetchRuns(): Promise<RunSummary[]> {
  try {
    const data = await call<{ runs: RunSummary[] }>('/api/runs');
    return data.runs;
  } catch {
    return [];
  }
}

export async function fetchRun(id: string): Promise<AnalysisReport | null> {
  try {
    return await call<AnalysisReport>(`/api/runs/${encodeURIComponent(id)}`);
  } catch {
    return null;
  }
}

/** The most recent run on the server, or null when there are none. */
export async function fetchLatestRun(): Promise<AnalysisReport | null> {
  const runs = await fetchRuns();
  return runs.length > 0 ? fetchRun(runs[0].id) : null;
}

/**
 * Send a video to the engine and get back the path it landed on.
 *
 * The body is the raw file, not multipart: the engine needs the bytes on
 * disk and nothing else, and a multipart envelope would mean parsing a
 * boundary-delimited stream server-side to recover exactly what the browser
 * already has. The filename travels in a header instead.
 */
export async function uploadVideo(
  file: File,
  timeoutMs = 30 * 60 * 1000,
): Promise<{ path: string; name: string; bytes: number }> {
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), timeoutMs);
  try {
    const response = await fetch(`${BASE}/api/upload`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/octet-stream',
        'X-Filename': file.name,
      },
      body: file,
      signal: controller.signal,
    });
    if (!response.ok) {
      const detail = await response.json().catch(() => ({ error: response.statusText }));
      throw new Error(detail.error ?? `upload failed (${response.status})`);
    }
    return await response.json();
  } finally {
    clearTimeout(timer);
  }
}

export interface StageEvent {
  seq: number;
  type:
    | 'run.start'
    | 'stage.start'
    | 'stage.end'
    | 'run.complete'
    | 'run.error'
    | 'fix.progress';
  stage?: string;
  agentId?: string;
  name?: string;
  status?: string;
  coverage?: number;
  elapsedMs?: number;
  findings?: number;
  calls?: number;
  detail?: string;
  error?: string;
  id?: string;
  topology?: { id: string; tier: number; parents: string[] }[];
  /** fix.progress only — which phase of the render is running. */
  stage_label?: string;
  ops?: number;
  output?: string;
  rendered?: boolean;
}

/**
 * Start a run and watch it happen.
 *
 * The synchronous route answers only when everything is finished — minutes
 * of silence on a hosted run, which is indistinguishable from a hang. This
 * returns immediately and streams each agent as it starts and settles.
 *
 * Returns a disposer. Call it to stop listening; the analysis continues
 * server-side and its report still lands on disk.
 */
export async function startJob(
  video: string,
  options: { offline?: boolean; budget?: number; strategy?: string },
  onEvent: (event: StageEvent) => void,
): Promise<() => void> {
  const started = await call<{ id: string }>(
    '/api/jobs',
    {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ video, ...options }),
    },
    READ_TIMEOUT_MS,
  );

  const stream = new EventSource(`${BASE}/api/events/${started.id}`);
  stream.onmessage = (message) => {
    try {
      const event = JSON.parse(message.data) as StageEvent;
      onEvent(event);
      // The server closes after the terminal event; closing here too stops
      // EventSource reconnecting and replaying a finished run forever.
      if (event.type === 'run.complete' || event.type === 'run.error') stream.close();
    } catch {
      /* a malformed frame must not kill the stream */
    }
  };
  stream.onerror = () => stream.close();

  return () => stream.close();
}

/**
 * Compile and render the remediation, streaming progress.
 *
 * The Apply control was a label with no handler — the worst kind of broken,
 * because the plan and the ffmpeg command beside it are both real and only
 * the one button that would act on them did nothing.
 */
export async function applyFix(
  video: string,
  options: { offline?: boolean; strategy?: string },
  onEvent: (event: StageEvent) => void,
): Promise<() => void> {
  const started = await call<{ id: string }>(
    '/api/fix',
    {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ video, ...options }),
    },
    READ_TIMEOUT_MS,
  );

  const stream = new EventSource(`${BASE}/api/events/${started.id}`);
  stream.onmessage = (message) => {
    try {
      const event = JSON.parse(message.data) as StageEvent;
      onEvent(event);
      if (event.type === 'run.complete' || event.type === 'run.error') stream.close();
    } catch {
      /* a malformed frame must not kill the stream */
    }
  };
  stream.onerror = () => stream.close();
  return () => stream.close();
}

export async function analyze(
  video: string,
  options: { offline?: boolean; budget?: number; strategy?: string } = {},
): Promise<{ id: string; report: AnalysisReport }> {
  return call<{ id: string; report: AnalysisReport }>(
    '/api/analyze',
    {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ video, ...options }),
    },
    ANALYZE_TIMEOUT_MS,
  );
}
