import type { AnalysisReport } from '@/types/analysis';

/**
 * The engine, over HTTP.
 *
 * Three sources feed the deck, in this order of trust:
 *
 *   1. `window.__PREFLIGHT_REPORT__` — the CLI injected a real run into
 *      report.html. Already on the page, needs no network.
 *   2. This API — `preflight serve` is running and has real runs on disk.
 *   3. The demo fixture — itself generated by a real run, not authored.
 *
 * Every call fails soft. A deck that renders the fixture is useful; a deck
 * that renders a stack trace because the API is not running is not, and the
 * API being absent is the normal state when someone opens a report.html
 * someone else emailed them.
 */

const BASE = (import.meta.env.VITE_PREFLIGHT_API as string | undefined) ?? 'http://127.0.0.1:8000';

/** Long enough for a real analysis, short enough that a dead port is obvious. */
const ANALYZE_TIMEOUT_MS = 15 * 60 * 1000;
const READ_TIMEOUT_MS = 4000;

export interface RunSummary {
  id: string;
  filename: string;
  durationMs: number;
  overall: number | null;
  verdict: string | null;
  weakest: string | null;
  findingCount: number;
  coverage: number | null;
  analyzedAt: string | null;
}

export interface Health {
  status: string;
  engineVersion: string;
  ffmpeg: string | null;
  ffmpegAvailable: boolean;
  online: boolean;
  capabilities: Record<string, { tier: string; degraded: boolean }>;
  capabilitySummary: { preferred: number; fallback: number; unavailable: number };
}

async function call<T>(path: string, init?: RequestInit, timeoutMs = READ_TIMEOUT_MS): Promise<T> {
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), timeoutMs);
  try {
    const response = await fetch(`${BASE}${path}`, { ...init, signal: controller.signal });
    if (!response.ok) {
      // The API answers errors as JSON; fall back to the status line when it
      // is something else entirely (a proxy, a wrong port).
      const detail = await response.json().catch(() => ({ error: response.statusText }));
      throw new Error(detail.error ?? `HTTP ${response.status}`);
    }
    return (await response.json()) as T;
  } finally {
    clearTimeout(timer);
  }
}

/** Null when the API is not reachable — never throws. */
export async function fetchHealth(): Promise<Health | null> {
  try {
    return await call<Health>('/api/health');
  } catch {
    return null;
  }
}

export async function fetchRuns(): Promise<RunSummary[]> {
  try {
    const data = await call<{ runs: RunSummary[] }>('/api/runs');
    return data.runs;
  } catch {
    return [];
  }
}

export async function fetchRun(id: string): Promise<AnalysisReport | null> {
  try {
    return await call<AnalysisReport>(`/api/runs/${encodeURIComponent(id)}`);
  } catch {
    return null;
  }
}

/** The most recent run on the server, or null when there are none. */
export async function fetchLatestRun(): Promise<AnalysisReport | null> {
  const runs = await fetchRuns();
  return runs.length > 0 ? fetchRun(runs[0].id) : null;
}

export async function analyze(
  video: string,
  options: { offline?: boolean; budget?: number; strategy?: string } = {},
): Promise<{ id: string; report: AnalysisReport }> {
  return call<{ id: string; report: AnalysisReport }>(
    '/api/analyze',
    {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ video, ...options }),
    },
    ANALYZE_TIMEOUT_MS,
  );
}
