import type { AnalysisReport } from '@/types/analysis';
import { beforeReport } from '@/data/fixture';

/**
 * Where the page gets its data.
 *
 * When the CLI emits report.html it injects the real analysis as
 * `window.__PREFLIGHT_REPORT__` before the bundle runs, so the page renders
 * that. In dev, and when the bundle is served standalone, it falls back to the
 * demo fixture — which is itself generated by a real run, not authored.
 *
 * This is the whole integration surface between the engine and the UI.
 */

declare global {
  interface Window {
    __PREFLIGHT_REPORT__?: AnalysisReport;
    __PREFLIGHT_REPORT_AFTER__?: AnalysisReport;
  }
}

export function injectedReport(): AnalysisReport | null {
  return typeof window === 'undefined' ? null : (window.__PREFLIGHT_REPORT__ ?? null);
}

export function injectedAfterReport(): AnalysisReport | null {
  return typeof window === 'undefined' ? null : (window.__PREFLIGHT_REPORT_AFTER__ ?? null);
}

/** True when the page is rendering real CLI output rather than the fixture. */
export function isLiveReport(): boolean {
  return injectedReport() !== null;
}

export function initialReport(): AnalysisReport {
  return injectedReport() ?? beforeReport;
}
